version: "3.8"
services:
  nginx:
    build:
      context: ./nginx
    restart: always
    image: matheusfols/nginx-fc
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

  app:
    platform: linux/amd64
    build:
      context: ./node
    container_name: app
    image: matheusfols/node-fc
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 60s npm run start
    # entrypoint: wait-for db:3306 -t 40 -- npm run start
    entrypoint: sh -c "npm install && npm run start"
    tty: true
    networks:
      - node-network
    ports:
      - "5000:5000"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    platform: linux/amd64
    image: mariadb:10.5.8
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    healthcheck:
      test: [ "CMD", "mariadb", "-uroot", "-proot" ]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  mysql:
    driver: local
