version: "3.8"
services:
  nginx:
    build:
      context: ./nginx
    image: matheusfols/nginx-fc
    restart: always
    container_name: nginx
    ports:
      - "8080:80"

  app:
    build:
      context: ./node
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
